const visitors = [
    { link: '', src: '/img/logos/grupoPosadas.webp', alt:'Grupo Posadas', width: 200, height: 190 },
    { link: '', src: '/img/logos/femsa.webp', alt:'Interjet', width: 200, height: 190 },
    { link: '', src: '/img/logos/tecMonterrery.webp', alt:'Latam', width: 150, height: 190 },
    { link: '', src: '/img/logos/cemex.webp', alt:'Tec de Monterrey', width: 200, height: 190 },
    { link: '', src: '/img/logos/ternium.webp', alt:'Cemex', width: 200, height: 190 },
    { link: '', src: '/img/logos/exhibitors/siemens_02.webp', alt:'', width: 230, height: 97.29 },
    { link: '', src: '/img/logos/exhibitors/3m.webp', alt:'', width: 150, height: 124 },
    { link: '', src: '/img/logos/deloitte.webp', alt:'', width: 200, height: 124 },

]

const partners = [
    { link: '', src: '/img/logos/cluster-industrial.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/heraldo_group.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/vanguardia-industrial.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/negocio-motor.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/negocio-transporte.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/logistic-delivery.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/dpl-news.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/global-industries_v2.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/consultoria.webp', alt:'', width: 200, height: 190 }, 
    { link: '', src: '/img/logos/global-energy-v2.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/energia-hoy.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/empresas-verdes.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/Energy-Commerce.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/directorioauto.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/Milenio.webp', alt:'', width: 200, height: 190 },
    { link: '', src: '/img/logos/Industria360.webp', alt:'', width: 250, height: 190 },
    { link: '', src: '/img/logos/cuatrocero_v2.webp', alt:'', width: 200, },
    { link: '', src: '/img/logos/mexicoindustry.webp', alt:'', width: 200,  },
    { link: '', src: '/img/logos/movilidad3.webp', alt:'', width: 200,  },
]


const exhibitors = [
    { link: '', src: '/img/logos/exhibitors/siemens_02.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/kia.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/hitachi.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/3m.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/360.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/acsys.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/airmobility.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/allride.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/bendix.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/cenex.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/centro_empresarial.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/cii.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/fedex.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/filtermist.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/gob_monterrey.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/gsm.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/hellman.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/hirst.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/idonis.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/introid.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/japma.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/keysight.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/machine_care.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/mit.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/mtd.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/nemak.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/nuevo_leon.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/pymatek.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/sgs.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/sliding.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/tr.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/uanl.webp', alt:'', width: 200, height: 124 },
    { link: '', src: '/img/logos/exhibitors/voltway.webp', alt:'', width: 200, height: 124 },
]

export {partners, exhibitors ,visitors}